'use strict';
const fs=require('fs'),assert=require('assert');
const runtime=fs.readFileSync('bbma-runtime.js','utf8');
const router=fs.readFileSync('bbma-router-fix.js','utf8');
const prep=fs.readFileSync('tools/prepare-web.js','utf8');
assert(runtime.includes('out.mtf=out.frames'),'runtime must expose frames through dashboard mtf contract');
assert(runtime.includes('out.timeframes=out.frames'),'runtime must expose timeframes compatibility contract');
assert(runtime.includes('ohlc:frames'),'runtime OHLC missing');
assert(router.includes("stopImmediatePropagation"),'router must stop legacy BBMA click handler from competing');
assert(router.includes("bb.style.display='none'"),'leaving BBMA must hide the dashboard');
assert(router.includes("bbma-alert-open"),'deep-link alerts must route to BBMA');
assert(prep.includes('bbma-router-fix.js'),'APK bundle must include BBMA router fix');
console.log('BBMA APK router/runtime contract passed');
