/* Auto-generated by build-atr.js - real daily OHLC from Yahoo Finance / Coinbase, Wilder ATR(14).
 * Regenerated by the daily cron job. Loaded via <script src> so file:// works.
 */
window.ATR_DATA = {
  "asOf": "2026-09-25 04:20:41",
  "period": 14,
  "rows": [
    {
      "id": "EURUSD",
      "label": "EUR/USD",
      "group": "Forex",
      "atr": 0.005155,
      "last": 1.137268,
      "atrPct": 0.4533,
      "bars": 67,
      "src": "yahoo:EURUSD=X"
    },
    {
      "id": "GBPUSD",
      "label": "GBP/USD",
      "group": "Forex",
      "atr": 0.006958,
      "last": 1.321231,
      "atrPct": 0.5266,
      "bars": 67,
      "src": "yahoo:GBPUSD=X"
    },
    {
      "id": "USDJPY",
      "label": "USD/JPY",
      "group": "Forex",
      "atr": 1.393525,
      "last": 158.328003,
      "atrPct": 0.8802,
      "bars": 67,
      "src": "yahoo:USDJPY=X"
    },
    {
      "id": "USDCHF",
      "label": "USD/CHF",
      "group": "Forex",
      "atr": 0.005317,
      "last": 0.82909,
      "atrPct": 0.6414,
      "bars": 67,
      "src": "yahoo:USDCHF=X"
    },
    {
      "id": "AUDUSD",
      "label": "AUD/USD",
      "group": "Forex",
      "atr": 0.004786,
      "last": 0.701557,
      "atrPct": 0.6822,
      "bars": 67,
      "src": "yahoo:AUDUSD=X"
    },
    {
      "id": "NZDUSD",
      "label": "NZD/USD",
      "group": "Forex",
      "atr": 0.004725,
      "last": 0.565419,
      "atrPct": 0.8357,
      "bars": 67,
      "src": "yahoo:NZDUSD=X"
    },
    {
      "id": "USDCAD",
      "label": "USD/CAD",
      "group": "Forex",
      "atr": 0.006566,
      "last": 1.4148,
      "atrPct": 0.4641,
      "bars": 67,
      "src": "yahoo:USDCAD=X"
    },
    {
      "id": "EURGBP",
      "label": "EUR/GBP",
      "group": "Forex",
      "atr": 0.002276,
      "last": 0.86054,
      "atrPct": 0.2645,
      "bars": 67,
      "src": "yahoo:EURGBP=X"
    },
    {
      "id": "EURJPY",
      "label": "EUR/JPY",
      "group": "Forex",
      "atr": 1.338512,
      "last": 180.024002,
      "atrPct": 0.7435,
      "bars": 67,
      "src": "yahoo:EURJPY=X"
    },
    {
      "id": "GBPJPY",
      "label": "GBP/JPY",
      "group": "Forex",
      "atr": 1.639617,
      "last": 209.192001,
      "atrPct": 0.7838,
      "bars": 67,
      "src": "yahoo:GBPJPY=X"
    },
    {
      "id": "EURCHF",
      "label": "EUR/CHF",
      "group": "Forex",
      "atr": 0.003919,
      "last": 0.94268,
      "atrPct": 0.4157,
      "bars": 67,
      "src": "yahoo:EURCHF=X"
    },
    {
      "id": "AUDJPY",
      "label": "AUD/JPY",
      "group": "Forex",
      "atr": 0.959606,
      "last": 111.042999,
      "atrPct": 0.8642,
      "bars": 67,
      "src": "yahoo:AUDJPY=X"
    },
    {
      "id": "CADJPY",
      "label": "CAD/JPY",
      "group": "Forex",
      "atr": 0.896091,
      "last": 111.906998,
      "atrPct": 0.8007,
      "bars": 67,
      "src": "yahoo:CADJPY=X"
    },
    {
      "id": "CHFJPY",
      "label": "CHF/JPY",
      "group": "Forex",
      "atr": 1.621364,
      "last": 190.942001,
      "atrPct": 0.8491,
      "bars": 67,
      "src": "yahoo:CHFJPY=X"
    },
    {
      "id": "NZDJPY",
      "label": "NZD/JPY",
      "group": "Forex",
      "atr": 0.813925,
      "last": 89.491997,
      "atrPct": 0.9095,
      "bars": 67,
      "src": "yahoo:NZDJPY=X"
    },
    {
      "id": "EURAUD",
      "label": "EUR/AUD",
      "group": "Forex",
      "atr": 0.007611,
      "last": 1.62109,
      "atrPct": 0.4695,
      "bars": 67,
      "src": "yahoo:EURAUD=X"
    },
    {
      "id": "GBPAUD",
      "label": "GBP/AUD",
      "group": "Forex",
      "atr": 0.008626,
      "last": 1.88377,
      "atrPct": 0.4579,
      "bars": 67,
      "src": "yahoo:GBPAUD=X"
    },
    {
      "id": "AUDNZD",
      "label": "AUD/NZD",
      "group": "Forex",
      "atr": 0.007089,
      "last": 1.24065,
      "atrPct": 0.5714,
      "bars": 67,
      "src": "yahoo:AUDNZD=X"
    },
    {
      "id": "BTCUSD",
      "label": "BTC/USD",
      "group": "Crypto",
      "atr": 2419.333075,
      "last": 84134.5,
      "atrPct": 2.8756,
      "bars": 350,
      "src": "coinbase:BTC-USD"
    },
    {
      "id": "ETHUSD",
      "label": "ETH/USD",
      "group": "Crypto",
      "atr": 99.239182,
      "last": 2675.46,
      "atrPct": 3.7092,
      "bars": 350,
      "src": "coinbase:ETH-USD"
    },
    {
      "id": "SOLUSD",
      "label": "SOL/USD",
      "group": "Crypto",
      "atr": 5.193923,
      "last": 116.56,
      "atrPct": 4.456,
      "bars": 350,
      "src": "coinbase:SOL-USD"
    },
    {
      "id": "XAUUSD",
      "label": "Gold (XAU)",
      "group": "Commodity",
      "atr": 95.545303,
      "last": 4305.200195,
      "atrPct": 2.2193,
      "bars": 65,
      "src": "yahoo:GC=F"
    },
    {
      "id": "XAGUSD",
      "label": "Silver (XAG)",
      "group": "Commodity",
      "atr": 1.545821,
      "last": 64.044998,
      "atrPct": 2.4136,
      "bars": 65,
      "src": "yahoo:SI=F"
    },
    {
      "id": "BRENT",
      "label": "Brent crude",
      "group": "Commodity",
      "atr": 4.410839,
      "last": 105.559998,
      "atrPct": 4.1785,
      "bars": 65,
      "src": "yahoo:BZ=F"
    },
    {
      "id": "WTI",
      "label": "WTI crude",
      "group": "Commodity",
      "atr": 4.453695,
      "last": 93.050003,
      "atrPct": 4.7863,
      "bars": 65,
      "src": "yahoo:CL=F"
    },
    {
      "id": "COPPER",
      "label": "Copper",
      "group": "Commodity",
      "atr": 0.106196,
      "last": 6.745,
      "atrPct": 1.5744,
      "bars": 65,
      "src": "yahoo:HG=F"
    },
    {
      "id": "PLATINUM",
      "label": "Platinum",
      "group": "Commodity",
      "atr": 27.855614,
      "last": 1751.099976,
      "atrPct": 1.5907,
      "bars": 65,
      "src": "yahoo:PL=F"
    }
  ]
};
