/* Auto-generated by build-atr.js - real daily OHLC from Yahoo Finance / Coinbase, Wilder ATR(14).
 * Regenerated by the daily cron job. Loaded via <script src> so file:// works.
 */
window.ATR_DATA = {
  "asOf": "2026-10-10 05:49:35",
  "period": 14,
  "rows": [
    {
      "id": "EURUSD",
      "label": "EUR/USD",
      "group": "Forex",
      "atr": 0.006465,
      "last": 1.120574,
      "atrPct": 0.5769,
      "bars": 68,
      "src": "yahoo:EURUSD=X"
    },
    {
      "id": "GBPUSD",
      "label": "GBP/USD",
      "group": "Forex",
      "atr": 0.006876,
      "last": 1.323311,
      "atrPct": 0.5196,
      "bars": 68,
      "src": "yahoo:GBPUSD=X"
    },
    {
      "id": "USDJPY",
      "label": "USD/JPY",
      "group": "Forex",
      "atr": 1.142597,
      "last": 158.246002,
      "atrPct": 0.722,
      "bars": 68,
      "src": "yahoo:USDJPY=X"
    },
    {
      "id": "USDCHF",
      "label": "USD/CHF",
      "group": "Forex",
      "atr": 0.004988,
      "last": 0.83,
      "atrPct": 0.601,
      "bars": 68,
      "src": "yahoo:USDCHF=X"
    },
    {
      "id": "AUDUSD",
      "label": "AUD/USD",
      "group": "Forex",
      "atr": 0.00468,
      "last": 0.698763,
      "atrPct": 0.6697,
      "bars": 68,
      "src": "yahoo:AUDUSD=X"
    },
    {
      "id": "NZDUSD",
      "label": "NZD/USD",
      "group": "Forex",
      "atr": 0.003977,
      "last": 0.561199,
      "atrPct": 0.7086,
      "bars": 68,
      "src": "yahoo:NZDUSD=X"
    },
    {
      "id": "USDCAD",
      "label": "USD/CAD",
      "group": "Forex",
      "atr": 0.006264,
      "last": 1.4254,
      "atrPct": 0.4394,
      "bars": 68,
      "src": "yahoo:USDCAD=X"
    },
    {
      "id": "EURGBP",
      "label": "EUR/GBP",
      "group": "Forex",
      "atr": 0.003001,
      "last": 0.84611,
      "atrPct": 0.3546,
      "bars": 68,
      "src": "yahoo:EURGBP=X"
    },
    {
      "id": "EURJPY",
      "label": "EUR/JPY",
      "group": "Forex",
      "atr": 1.379084,
      "last": 177.100006,
      "atrPct": 0.7787,
      "bars": 68,
      "src": "yahoo:EURJPY=X"
    },
    {
      "id": "GBPJPY",
      "label": "GBP/JPY",
      "group": "Forex",
      "atr": 1.538372,
      "last": 209.505997,
      "atrPct": 0.7343,
      "bars": 68,
      "src": "yahoo:GBPJPY=X"
    },
    {
      "id": "EURCHF",
      "label": "EUR/CHF",
      "group": "Forex",
      "atr": 0.005705,
      "last": 0.92948,
      "atrPct": 0.6137,
      "bars": 68,
      "src": "yahoo:EURCHF=X"
    },
    {
      "id": "AUDJPY",
      "label": "AUD/JPY",
      "group": "Forex",
      "atr": 0.944559,
      "last": 110.568001,
      "atrPct": 0.8543,
      "bars": 68,
      "src": "yahoo:AUDJPY=X"
    },
    {
      "id": "CADJPY",
      "label": "CAD/JPY",
      "group": "Forex",
      "atr": 0.852606,
      "last": 111.009003,
      "atrPct": 0.7681,
      "bars": 68,
      "src": "yahoo:CADJPY=X"
    },
    {
      "id": "CHFJPY",
      "label": "CHF/JPY",
      "group": "Forex",
      "atr": 1.479476,
      "last": 190.653,
      "atrPct": 0.776,
      "bars": 68,
      "src": "yahoo:CHFJPY=X"
    },
    {
      "id": "NZDJPY",
      "label": "NZD/JPY",
      "group": "Forex",
      "atr": 0.74908,
      "last": 88.808998,
      "atrPct": 0.8435,
      "bars": 68,
      "src": "yahoo:NZDJPY=X"
    },
    {
      "id": "EURAUD",
      "label": "EUR/AUD",
      "group": "Forex",
      "atr": 0.008919,
      "last": 1.6029,
      "atrPct": 0.5565,
      "bars": 68,
      "src": "yahoo:EURAUD=X"
    },
    {
      "id": "GBPAUD",
      "label": "GBP/AUD",
      "group": "Forex",
      "atr": 0.009334,
      "last": 1.89437,
      "atrPct": 0.4927,
      "bars": 68,
      "src": "yahoo:GBPAUD=X"
    },
    {
      "id": "AUDNZD",
      "label": "AUD/NZD",
      "group": "Forex",
      "atr": 0.006373,
      "last": 1.24449,
      "atrPct": 0.5121,
      "bars": 68,
      "src": "yahoo:AUDNZD=X"
    },
    {
      "id": "BTCUSD",
      "label": "BTC/USD",
      "group": "Crypto",
      "atr": 2122.550113,
      "last": 82724.95,
      "atrPct": 2.5658,
      "bars": 350,
      "src": "coinbase:BTC-USD"
    },
    {
      "id": "ETHUSD",
      "label": "ETH/USD",
      "group": "Crypto",
      "atr": 84.667563,
      "last": 2495.48,
      "atrPct": 3.3928,
      "bars": 350,
      "src": "coinbase:ETH-USD"
    },
    {
      "id": "SOLUSD",
      "label": "SOL/USD",
      "group": "Crypto",
      "atr": 4.784137,
      "last": 110.09,
      "atrPct": 4.3457,
      "bars": 350,
      "src": "coinbase:SOL-USD"
    },
    {
      "id": "XAUUSD",
      "label": "Gold (XAU)",
      "group": "Commodity",
      "atr": 88.718367,
      "last": 4216.299805,
      "atrPct": 2.1042,
      "bars": 65,
      "src": "yahoo:GC=F"
    },
    {
      "id": "XAGUSD",
      "label": "Silver (XAG)",
      "group": "Commodity",
      "atr": 1.421671,
      "last": 60.669998,
      "atrPct": 2.3433,
      "bars": 65,
      "src": "yahoo:SI=F"
    },
    {
      "id": "BRENT",
      "label": "Brent crude",
      "group": "Commodity",
      "atr": 4.410323,
      "last": 104.720001,
      "atrPct": 4.2115,
      "bars": 65,
      "src": "yahoo:BZ=F"
    },
    {
      "id": "WTI",
      "label": "WTI crude",
      "group": "Commodity",
      "atr": 4.258831,
      "last": 91.849998,
      "atrPct": 4.6367,
      "bars": 65,
      "src": "yahoo:CL=F"
    },
    {
      "id": "COPPER",
      "label": "Copper",
      "group": "Commodity",
      "atr": 0.090682,
      "last": 6.6425,
      "atrPct": 1.3652,
      "bars": 65,
      "src": "yahoo:HG=F"
    },
    {
      "id": "PLATINUM",
      "label": "Platinum",
      "group": "Commodity",
      "atr": 35.895503,
      "last": 1679.300049,
      "atrPct": 2.1375,
      "bars": 64,
      "src": "yahoo:PL=F"
    }
  ]
};
