/* Auto-generated by build-atr.js - real daily OHLC from Yahoo Finance / Coinbase, Wilder ATR(14).
 * Regenerated by the daily cron job. Loaded via <script src> so file:// works.
 */
window.ATR_DATA = {
  "asOf": "2026-09-18 04:05:04",
  "period": 14,
  "rows": [
    {
      "id": "EURUSD",
      "label": "EUR/USD",
      "group": "Forex",
      "atr": 0.005057,
      "last": 1.149425,
      "atrPct": 0.44,
      "bars": 67,
      "src": "yahoo:EURUSD=X"
    },
    {
      "id": "GBPUSD",
      "label": "GBP/USD",
      "group": "Forex",
      "atr": 0.00642,
      "last": 1.337453,
      "atrPct": 0.48,
      "bars": 67,
      "src": "yahoo:GBPUSD=X"
    },
    {
      "id": "USDJPY",
      "label": "USD/JPY",
      "group": "Forex",
      "atr": 1.480521,
      "last": 157.037003,
      "atrPct": 0.9428,
      "bars": 67,
      "src": "yahoo:USDJPY=X"
    },
    {
      "id": "USDCHF",
      "label": "USD/CHF",
      "group": "Forex",
      "atr": 0.005211,
      "last": 0.82302,
      "atrPct": 0.6331,
      "bars": 67,
      "src": "yahoo:USDCHF=X"
    },
    {
      "id": "AUDUSD",
      "label": "AUD/USD",
      "group": "Forex",
      "atr": 0.004402,
      "last": 0.713725,
      "atrPct": 0.6168,
      "bars": 67,
      "src": "yahoo:AUDUSD=X"
    },
    {
      "id": "NZDUSD",
      "label": "NZD/USD",
      "group": "Forex",
      "atr": 0.004707,
      "last": 0.573822,
      "atrPct": 0.8203,
      "bars": 67,
      "src": "yahoo:NZDUSD=X"
    },
    {
      "id": "USDCAD",
      "label": "USD/CAD",
      "group": "Forex",
      "atr": 0.006522,
      "last": 1.39765,
      "atrPct": 0.4666,
      "bars": 67,
      "src": "yahoo:USDCAD=X"
    },
    {
      "id": "EURGBP",
      "label": "EUR/GBP",
      "group": "Forex",
      "atr": 0.002398,
      "last": 0.85908,
      "atrPct": 0.2792,
      "bars": 67,
      "src": "yahoo:EURGBP=X"
    },
    {
      "id": "EURJPY",
      "label": "EUR/JPY",
      "group": "Forex",
      "atr": 1.433061,
      "last": 180.470993,
      "atrPct": 0.7941,
      "bars": 67,
      "src": "yahoo:EURJPY=X"
    },
    {
      "id": "GBPJPY",
      "label": "GBP/JPY",
      "group": "Forex",
      "atr": 1.745797,
      "last": 210.044006,
      "atrPct": 0.8312,
      "bars": 67,
      "src": "yahoo:GBPJPY=X"
    },
    {
      "id": "EURCHF",
      "label": "EUR/CHF",
      "group": "Forex",
      "atr": 0.003486,
      "last": 0.94569,
      "atrPct": 0.3687,
      "bars": 67,
      "src": "yahoo:EURCHF=X"
    },
    {
      "id": "AUDJPY",
      "label": "AUD/JPY",
      "group": "Forex",
      "atr": 0.989768,
      "last": 112.042999,
      "atrPct": 0.8834,
      "bars": 67,
      "src": "yahoo:AUDJPY=X"
    },
    {
      "id": "CADJPY",
      "label": "CAD/JPY",
      "group": "Forex",
      "atr": 0.992013,
      "last": 112.366997,
      "atrPct": 0.8828,
      "bars": 67,
      "src": "yahoo:CADJPY=X"
    },
    {
      "id": "CHFJPY",
      "label": "CHF/JPY",
      "group": "Forex",
      "atr": 1.727724,
      "last": 190.862,
      "atrPct": 0.9052,
      "bars": 67,
      "src": "yahoo:CHFJPY=X"
    },
    {
      "id": "NZDJPY",
      "label": "NZD/JPY",
      "group": "Forex",
      "atr": 0.882532,
      "last": 90.110001,
      "atrPct": 0.9794,
      "bars": 67,
      "src": "yahoo:NZDJPY=X"
    },
    {
      "id": "EURAUD",
      "label": "EUR/AUD",
      "group": "Forex",
      "atr": 0.007365,
      "last": 1.6104,
      "atrPct": 0.4573,
      "bars": 67,
      "src": "yahoo:EURAUD=X"
    },
    {
      "id": "GBPAUD",
      "label": "GBP/AUD",
      "group": "Forex",
      "atr": 0.00953,
      "last": 1.87449,
      "atrPct": 0.5084,
      "bars": 67,
      "src": "yahoo:GBPAUD=X"
    },
    {
      "id": "AUDNZD",
      "label": "AUD/NZD",
      "group": "Forex",
      "atr": 0.007262,
      "last": 1.24341,
      "atrPct": 0.584,
      "bars": 67,
      "src": "yahoo:AUDNZD=X"
    },
    {
      "id": "BTCUSD",
      "label": "BTC/USD",
      "group": "Crypto",
      "atr": 2103.940885,
      "last": 77334.36,
      "atrPct": 2.7206,
      "bars": 350,
      "src": "coinbase:BTC-USD"
    },
    {
      "id": "ETHUSD",
      "label": "ETH/USD",
      "group": "Crypto",
      "atr": 93.967743,
      "last": 2477.5,
      "atrPct": 3.7928,
      "bars": 350,
      "src": "coinbase:ETH-USD"
    },
    {
      "id": "SOLUSD",
      "label": "SOL/USD",
      "group": "Crypto",
      "atr": 4.583903,
      "last": 104.66,
      "atrPct": 4.3798,
      "bars": 350,
      "src": "coinbase:SOL-USD"
    },
    {
      "id": "XAUUSD",
      "label": "Gold (XAU)",
      "group": "Commodity",
      "atr": 111.695043,
      "last": 4399.700195,
      "atrPct": 2.5387,
      "bars": 63,
      "src": "yahoo:GC=F"
    },
    {
      "id": "XAGUSD",
      "label": "Silver (XAG)",
      "group": "Commodity",
      "atr": 1.743237,
      "last": 65.470001,
      "atrPct": 2.6626,
      "bars": 63,
      "src": "yahoo:SI=F"
    },
    {
      "id": "BRENT",
      "label": "Brent crude",
      "group": "Commodity",
      "atr": 4.324694,
      "last": 104.82,
      "atrPct": 4.1258,
      "bars": 63,
      "src": "yahoo:BZ=F"
    },
    {
      "id": "WTI",
      "label": "WTI crude",
      "group": "Commodity",
      "atr": 4.238628,
      "last": 101.910004,
      "atrPct": 4.1592,
      "bars": 63,
      "src": "yahoo:CL=F"
    },
    {
      "id": "COPPER",
      "label": "Copper",
      "group": "Commodity",
      "atr": 0.11789,
      "last": 6.5865,
      "atrPct": 1.7899,
      "bars": 63,
      "src": "yahoo:HG=F"
    },
    {
      "id": "PLATINUM",
      "label": "Platinum",
      "group": "Commodity",
      "atr": 29.801958,
      "last": 1791.400024,
      "atrPct": 1.6636,
      "bars": 63,
      "src": "yahoo:PL=F"
    }
  ]
};
