/* build-atr.js - fetch real daily OHLC and compute Wilder ATR(14) per instrument.
 * Writes atr.js -> window.ATR_DATA (script-tag loadable from file://).
 * Run: node build-atr.js
 */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'atr.js');

const INSTRUMENTS = [
  // id, label, group, yahoo symbol (null = use Coinbase), coinbase product
  ['EURUSD', 'EUR/USD', 'Forex', 'EURUSD=X', null],
  ['GBPUSD', 'GBP/USD', 'Forex', 'GBPUSD=X', null],
  ['USDJPY', 'USD/JPY', 'Forex', 'USDJPY=X', null],
  ['USDCHF', 'USD/CHF', 'Forex', 'USDCHF=X', null],
  ['AUDUSD', 'AUD/USD', 'Forex', 'AUDUSD=X', null],
  ['NZDUSD', 'NZD/USD', 'Forex', 'NZDUSD=X', null],
  ['USDCAD', 'USD/CAD', 'Forex', 'USDCAD=X', null],
  ['EURGBP', 'EUR/GBP', 'Forex', 'EURGBP=X', null],
  ['EURJPY', 'EUR/JPY', 'Forex', 'EURJPY=X', null],
  ['GBPJPY', 'GBP/JPY', 'Forex', 'GBPJPY=X', null],
  ['EURCHF', 'EUR/CHF', 'Forex', 'EURCHF=X', null],
  ['AUDJPY', 'AUD/JPY', 'Forex', 'AUDJPY=X', null],
  ['CADJPY', 'CAD/JPY', 'Forex', 'CADJPY=X', null],
  ['CHFJPY', 'CHF/JPY', 'Forex', 'CHFJPY=X', null],
  ['NZDJPY', 'NZD/JPY', 'Forex', 'NZDJPY=X', null],
  ['EURAUD', 'EUR/AUD', 'Forex', 'EURAUD=X', null],
  ['GBPAUD', 'GBP/AUD', 'Forex', 'GBPAUD=X', null],
  ['AUDNZD', 'AUD/NZD', 'Forex', 'AUDNZD=X', null],
  ['BTCUSD', 'BTC/USD', 'Crypto', null, 'BTC-USD'],
  ['ETHUSD', 'ETH/USD', 'Crypto', null, 'ETH-USD'],
  ['SOLUSD', 'SOL/USD', 'Crypto', null, 'SOL-USD'],
  ['XAUUSD', 'Gold (XAU)', 'Commodity', 'GC=F', null],
  ['XAGUSD', 'Silver (XAG)', 'Commodity', 'SI=F', null],
  ['BRENT', 'Brent crude', 'Commodity', 'BZ=F', null],
  ['WTI', 'WTI crude', 'Commodity', 'CL=F', null],
  ['COPPER', 'Copper', 'Commodity', 'HG=F', null],
  ['PLATINUM', 'Platinum', 'Commodity', 'PL=F', null]
];

const UA = { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' };
const sleep = ms => new Promise(r => setTimeout(r, ms));

async function yahooBars(sym) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=3mo&interval=1d`;
  const r = await fetch(url, { headers: UA });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const j = await r.json();
  const res = j.chart && j.chart.result && j.chart.result[0];
  if (!res) throw new Error('no result');
  const q = res.indicators.quote[0];
  const ts = res.timestamp || [];
  const bars = [];
  for (let i = 0; i < ts.length; i++) {
    if (q.open[i] == null || q.high[i] == null || q.low[i] == null || q.close[i] == null) continue;
    bars.push({ t: ts[i], o: q.open[i], h: q.high[i], l: q.low[i], c: q.close[i] });
  }
  return { bars, last: res.meta.regularMarketPrice = q.close[q.close.length - 1] };
}

async function coinbaseBars(product) {
  const url = `https://api.exchange.coinbase.com/products/${product}/candles?granularity=86400`;
  const r = await fetch(url, { headers: UA });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const j = await r.json();
  // [time, low, high, open, close, volume], newest first
  const bars = j.map(x => ({ t: x[0], l: x[1], h: x[2], o: x[3], c: x[4] })).sort((a, b) => a.t - b.t);
  return { bars, last: bars.length ? bars[bars.length - 1].c : null };
}

function atr(bars, period) {
  if (bars.length < period + 1) return null;
  const trs = [];
  for (let i = 1; i < bars.length; i++) {
    const b = bars[i], p = bars[i - 1];
    trs.push(Math.max(b.h - b.l, Math.abs(b.h - p.c), Math.abs(b.l - p.c)));
  }
  // Wilder smoothing
  let a = trs.slice(0, period).reduce((s, v) => s + v, 0) / period;
  for (let i = period; i < trs.length; i++) a = ((a * (period - 1)) + trs[i]) / period;
  return a;
}

(async () => {
  const out = { asOf: new Date().toISOString().slice(0, 19).replace('T', ' '), period: 14, rows: [] };
  let ok = 0, failCount = 0;
  for (const [id, label, group, ysym, cbp] of INSTRUMENTS) {
    try {
      const res = ysym ? await yahooBars(ysym) : await coinbaseBars(cbp);
      const a = atr(res.bars, 14);
      const last = res.last != null ? res.last : (res.bars[res.bars.length - 1] || {}).c;
      if (a == null || !last) throw new Error('insufficient bars');
      out.rows.push({ id, label, group, atr: +a.toFixed(6), last: +last.toFixed(6), atrPct: +((a / last) * 100).toFixed(4), bars: res.bars.length, src: ysym ? 'yahoo:' + ysym : 'coinbase:' + cbp });
      ok++;
      console.log('OK   ' + id.padEnd(9) + ' bars=' + String(res.bars.length).padStart(3) + '  last=' + String(last).padStart(12) + '  ATR14=' + a.toFixed(5) + '  (' + ((a / last) * 100).toFixed(3) + '%)');
    } catch (e) {
      failCount++;
      console.log('FAIL ' + id.padEnd(9) + ' -> ' + e.message);
    }
    await sleep(120);
  }
  const body = '/* Auto-generated by build-atr.js - real daily OHLC from Yahoo Finance / Coinbase, Wilder ATR(14).\n' +
    ' * Regenerated by the daily cron job. Loaded via <script src> so file:// works.\n */\n' +
    'window.ATR_DATA = ' + JSON.stringify(out, null, 2) + ';\n';
  fs.writeFileSync(OUT, body, 'utf8');
  console.log('\nwrote ' + OUT + ' with ' + ok + ' rows (' + failCount + ' failed)');
})();
