/* build-macro.js - fetches DXY, US 10Y yield and Brent crude from Yahoo Finance (same free,
 * key-free endpoint build-atr.js already uses) and writes them as an ADDITIVE override, same
 * pattern as build-news.js -> news-auto.js. Never edits xauusd-data.js directly.
 *
 * Why this exists: xauusd-data.js's "DXY / US 10Y / Brent / Sep hike odds" macro KPI cards were
 * hand-set once (16 Sep) and never refreshed by any script, even though ATR/news/calendar all
 * get a daily bot refresh - so those three numbers were silently going stale while everything
 * around them looked live. "Sep hike odds" (a CME FedWatch-style probability) has no free public
 * API and is intentionally left out - it stays whatever xauusd-data.js already has, or should be
 * dropped once it's clearly outdated.
 *
 * Output: macro-auto.js -> window.MACRO_AUTO = { generatedAt, dxy, us10y, brent }
 * Merge happens in the browser (see mergeMacroAuto() at the bottom), overwriting the gold tab's
 * first three macro KPI cards (DXY/US10Y/Brent slots) in place.
 *
 * Run: node build-macro.js   (same daily/frequent cron as build-atr.js / build-news.js)
 */
'use strict';
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'macro-auto.js');
const UA = { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' };

async function yahooQuote(symbol) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=5d&interval=1d`;
  const r = await fetch(url, { headers: UA });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const j = await r.json();
  const meta = j.chart && j.chart.result && j.chart.result[0] && j.chart.result[0].meta;
  if (!meta || meta.regularMarketPrice == null) throw new Error('no price in response');
  return { price: meta.regularMarketPrice, changePct: meta.regularMarketChangePercent };
}

function fmtDelta(pct, decimals) {
  if (pct == null || !isFinite(pct)) return '—';
  return (pct >= 0 ? '+' : '') + pct.toFixed(decimals || 2) + '%';
}

(async () => {
  console.log('build-macro.js - fetching DXY / US10Y / Brent from Yahoo Finance...\n');
  const out = { generatedAt: new Date().toISOString().slice(0, 19).replace('T', ' ') + 'Z' };

  try {
    const q = await yahooQuote('DX-Y.NYB');
    out.dxy = { label: 'DXY', value: q.price.toFixed(2), delta: fmtDelta(q.changePct), note: q.changePct >= 0 ? 'Dollar strengthening' : 'Dollar softening' };
    console.log('OK   DXY    ' + q.price.toFixed(2) + '  (' + fmtDelta(q.changePct) + ')');
  } catch (e) { console.log('FAIL DXY    -> ' + e.message); }

  try {
    const q = await yahooQuote('^TNX');
    out.us10y = { label: 'US 10Y', value: q.price.toFixed(3) + '%', delta: fmtDelta(q.changePct), note: q.price >= 4.5 ? 'Elevated real yields' : 'Yields easing' };
    console.log('OK   US10Y  ' + q.price.toFixed(3) + '%  (' + fmtDelta(q.changePct) + ')');
  } catch (e) { console.log('FAIL US10Y  -> ' + e.message); }

  try {
    const q = await yahooQuote('BZ=F');
    out.brent = { label: 'Brent', value: '$' + q.price.toFixed(2), delta: fmtDelta(q.changePct), note: q.changePct >= 1 ? 'Inflation-trade tailwind' : q.changePct <= -1 ? 'Cooling inflation pressure' : 'Steady' };
    console.log('OK   Brent  $' + q.price.toFixed(2) + '  (' + fmtDelta(q.changePct) + ')');
  } catch (e) { console.log('FAIL Brent  -> ' + e.message); }

  const body = '/* Auto-generated by build-macro.js - real Yahoo Finance quotes for DXY, US 10Y and Brent.\n' +
    ' * ADDITIVE ONLY - never edits xauusd-data.js. Merge happens in the browser, see mergeMacroAuto().\n' +
    ' * "Sep hike odds" is intentionally NOT here - no free public API for CME FedWatch-style data.\n' +
    ' * Regenerate: node build-macro.js (run on the same cron as build-atr.js / build-news.js).\n */\n' +
    'window.MACRO_AUTO = ' + JSON.stringify(out, null, 2) + ';\n\n' +
    '/* Overwrites the gold tab\'s DXY/US10Y/Brent macro KPI cards in place with live values.\n' +
    ' * Call AFTER xauusd-data.js is loaded, BEFORE app.js reads D. Leaves the 4th slot\n' +
    ' * ("Sep hike odds") untouched since there is no free source for it. */\n' +
    'window.mergeMacroAuto = function () {\n' +
    '  var D = window.MARKET_DATA, A = window.MACRO_AUTO;\n' +
    '  if (!D || !A) return;\n' +
    '  var gold = (D.tabs || []).filter(function (t) { return t.id === "gold"; })[0];\n' +
    '  if (!gold || !gold.macro) return;\n' +
    '  function apply(idx, live) { if (live && gold.macro[idx]) gold.macro[idx] = { label: live.label, value: live.value, delta: live.delta, note: live.note }; }\n' +
    '  apply(0, A.dxy); apply(1, A.us10y); apply(2, A.brent);\n' +
    '};\n' +
    'if (window.MARKET_DATA) window.mergeMacroAuto();\n';

  fs.writeFileSync(OUT, body, 'utf8');
  console.log('\nwrote ' + OUT);
})();
