/* Auto-generated by build-macro.js - real Yahoo Finance quotes for DXY, US 10Y and Brent.
 * ADDITIVE ONLY - never edits xauusd-data.js. Merge happens in the browser, see mergeMacroAuto().
 * "Sep hike odds" is intentionally NOT here - no free public API for CME FedWatch-style data.
 * Regenerate: node build-macro.js (run on the same cron as build-atr.js / build-news.js).
 */
window.MACRO_AUTO = {
  "generatedAt": "2026-09-22 04:14:39Z",
  "dxy": {
    "label": "DXY",
    "value": "100.37",
    "delta": "-0.06%",
    "note": "Dollar softening"
  },
  "us10y": {
    "label": "US 10Y",
    "value": "4.963%",
    "delta": "-0.70%",
    "note": "Elevated real yields"
  },
  "brent": {
    "label": "Brent",
    "value": "$97.19",
    "delta": "+0.99%",
    "note": "Steady"
  }
};

/* Overwrites the gold tab's DXY/US10Y/Brent macro KPI cards in place with live values.
 * Call AFTER xauusd-data.js is loaded, BEFORE app.js reads D. Leaves the 4th slot
 * ("Sep hike odds") untouched since there is no free source for it. */
window.mergeMacroAuto = function () {
  var D = window.MARKET_DATA, A = window.MACRO_AUTO;
  if (!D || !A) return;
  var gold = (D.tabs || []).filter(function (t) { return t.id === "gold"; })[0];
  if (!gold || !gold.macro) return;
  function apply(idx, live) { if (live && gold.macro[idx]) gold.macro[idx] = { label: live.label, value: live.value, delta: live.delta, note: live.note }; }
  apply(0, A.dxy); apply(1, A.us10y); apply(2, A.brent);
};
if (window.MARKET_DATA) window.mergeMacroAuto();
