/* Market desk data snapshot - Gold, Crypto, Forex + cross-asset + incoming events.
 * Regenerated by the daily cron job "Market Daily Brief + Speaker Watch".
 * index.html loads this file, then app.js renders it.
 *
 * RULES
 *  - Direction: hawkish speech -> SELL the risk asset / BUY USD ; dovish speech -> the inverse.
 *  - Speech impact: impactPct = BASE x speakerWeight x signalStrength x surpriseFactor
 *  - Range: see D.ranges.methods (realized range, ATR, options-implied, event study)
 */
window.MARKET_DATA = {
  updated: "2026-09-16 12:05 SGT",
  session: "FOMC day - decision ~18:00 GMT (17 Sep 02:00 SGT)",

  model: {
    base: 2.5,
    formula: "impact% = BASE x speakerWeight x signalStrength x surpriseFactor",
    note: "Model output - a transparent heuristic, NOT measured data.",
    weights: [ { k: "Fed Chair", v: 1.0 }, { k: "Central-bank decision / head", v: 0.9 }, { k: "FOMC voter", v: 0.8 }, { k: "Analyst / CIO", v: 0.35 }, { k: "Politician", v: 0.15 } ],
    strength: [ { k: "Actual policy decision", v: 1.0 }, { k: "Explicit forward guidance", v: 0.7 }, { k: "Vote / dissent", v: 0.6 }, { k: "Commentary", v: 0.4 }, { k: "Political pressure", v: 0.25 } ],
    surprise: [ { k: "Unpriced / surprise", v: 1.0 }, { k: "Partly priced", v: 0.5 }, { k: "Largely priced", v: 0.35 }, { k: "Fully priced / stale", v: 0.15 } ]
  },

  ranges: {
    note: "Four standard ways to size the range a news event can move. All four estimate dispersion; none is a prediction.",
    methods: [
      { name: "1. Realized range", formula: "range% = (High - Low) / Open x 100", use: "Range of the candle that contains the release.", caveat: "Backward-looking; needs the session closed." },
      { name: "2. ATR expected range", formula: "TR = max(High-Low, |High-PrevClose|, |Low-PrevClose|) ; ATR = 14-period mean of TR ; expected range = ATR x k", use: "k=1 normal day, k=1.5-2 for CPI / FOMC / NFP.", caveat: "Wilder smoothing: ATR_t = ((ATR_(t-1) x 13) + TR_t) / 14." },
      { name: "3. Options-implied move", formula: "expected move = Price x IV x sqrt(DTE / 365)", use: "Market-priced range for the event window.", caveat: "IV already embeds the event premium." },
      { name: "4. Event study (AR / CAR)", formula: "AR = R_asset - E(R_asset) ; CAR = sum(AR) over [t-1, t+1]", use: "Isolates the news effect from normal drift.", caveat: "Needs a baseline and a clean window." }
    ],
    prefill: { open: 4310, high: 4320, low: 4288, prevClose: 4306, atr: 42, iv: 18, dte: 1, k: 1.5 },
    prefillNote: "Illustrative defaults for XAU/USD - replace with your broker's OHLC, ATR(14) and IV."
  },

  /* ---- Incoming events: what to watch next + the timeframe to focus ---- */
  incoming: [
    { date: "16 Sep", timeMyt: "17 Sep 02:00", timeGmt: "16 Sep 18:00", event: "FOMC rate decision", importance: "high", note: "Consensus 25bp hike. First Fed hike in 3 years.", focusTf: "M5 - M15 for the spike, then H1", play: "Trade the second move after the knee-jerk: the dot plot and presser reprice the path.", source: "Federal Reserve", url: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm" },
    { date: "16 Sep", timeMyt: "17 Sep 02:30", timeGmt: "16 Sep 18:30", event: "FOMC press conference (Warsh)", importance: "high", note: "Tone decides 'one-and-done' vs a hiking cycle.", focusTf: "M15 - H1", play: "Highest-volatility window; spreads widen right after the statement.", source: "Federal Reserve", url: "https://www.federalreserve.gov/newsevents/pressreleases.htm" },
    { date: "17 Sep", timeMyt: "17 Sep 20:30", timeGmt: "17 Sep 12:30", event: "US initial jobless claims", importance: "med", note: "Labour-market read-through after the hike.", focusTf: "M5 - M15", play: "Only matters if it misses materially.", source: "US Dept. of Labor", url: "https://www.dol.gov/ui/data.pdf" },
    { date: "17 Sep", timeMyt: "17 Sep 20:30", timeGmt: "17 Sep 12:30", event: "Philadelphia Fed manufacturing index", importance: "med", note: "Growth pulse for the hawkish case.", focusTf: "M15", play: "Second-tier; fade extremes unless it contradicts the Fed.", source: "Philadelphia Fed", url: "https://www.philadelphiafed.org/surveys-and-data/regional-economic-analysis/manufacturing-business-outlook-survey" },
    { date: "18 Sep", timeMyt: "18 Sep 11:00", timeGmt: "18 Sep 03:00", event: "BoJ rate decision", importance: "high", note: "Another G3 hike would extend the global tightening move.", focusTf: "M15 - H4 (JPY crosses)", play: "JPY crosses move hardest; watch carry-unwind risk into crypto.", source: "Bank of Japan", url: "https://www.boj.or.jp/en/mopo/mpmsche_minu/index.htm" },
    { date: "18 Sep", timeMyt: "18 Sep 21:15", timeGmt: "18 Sep 13:15", event: "US August industrial production", importance: "med", note: "Closes out the week's US data.", focusTf: "M15", play: "Low impact unless far off consensus.", source: "Federal Reserve (G.17)", url: "https://www.federalreserve.gov/releases/g17/current/" }
  ],

  /* ---- Cross-asset transmission map ---- */
  crossAsset: {
    note: "How the four complex interlock. Read each row as: if the driver rises, what happens to the others.",
    headers: ["Driver up", "Gold", "Crypto", "USD (FX)", "Oil"],
    rows: [
      { driver: "USD / DXY", gold: "down", crypto: "down", fx: "-", oil: "down", note: "Dollar strength is the common denominator: it caps gold, crypto and dollar-priced oil." },
      { driver: "US real yields", gold: "down", crypto: "down", fx: "USD up", oil: "down", note: "Gold and crypto are both duration-like: higher real yields raise the opportunity cost." },
      { driver: "Oil price", gold: "mixed", crypto: "down", fx: "USD up*", oil: "-", note: "Higher oil raises inflation -> hawkish Fed -> USD up, risk assets down; but it also feeds gold's inflation hedge." },
      { driver: "Risk aversion", gold: "up", crypto: "down", fx: "USD/JPY down", oil: "down", note: "Gold is the haven; crypto trades as high-beta risk; JPY is the funding haven." },
      { driver: "Global tightening", gold: "down", crypto: "down", fx: "USD up", oil: "down", note: "ECB (10 Sep) and BoJ (18 Sep) hiking alongside the Fed drains liquidity." },
      { driver: "Central-bank gold buying", gold: "up", crypto: "-", fx: "-", oil: "-", note: "Record 288.9t in Q2 2026 - a structural bid under gold that metals-free assets do not get." }
    ],
    ratios: [
      { k: "Gold / Oil ratio", v: "~40.6x", note: "Gold $4,281 / Brent $105.5 - below the long-run average, i.e. oil is historically rich vs gold." },
      { k: "BTC / Gold ratio", v: "~18.1x", note: "BTC $77,700 / gold $4,281 - crypto still trades with risk appetite, not as digital gold." },
      { k: "DXY", v: "99.50", note: "The single best cross-asset signal: a fifth session of gains while gold and crypto fell." }
    ],
    oilNote: "Oil is currently the transmission belt: Brent ~$107 (Saudi pipeline shut) is pushing inflation expectations up, which is why the Fed is expected to hike.",
    sources: "Correlation structure: B2Prime - Trading Correlations: Gold, Oil & the USD; Investopedia - Iran war asset moves; Longtermtrends - gold/oil ratio."
  },

  /* ---- Live feed config ---- */
  live: {
    intervalSec: 5,
    fxEndpoint: "https://api.coinbase.com/v2/exchange-rates?currency=EUR",
    cryptoEndpoint: "https://api.coinbase.com/v2/exchange-rates?currency=BTC",
    note: "Key-free public endpoints, both verified reachable: Coinbase exchange-rates for FX (EUR table) and for crypto (BTC table). This is real network polling on an interval, not tick-by-tick streaming.",
    caveat: "If the browser blocks the request (CORS) or the machine is offline, the desk falls back to the last snapshot and the badge shows OFFLINE.",
    wsHint: "wss://stream.binance.com:9443/ws/btcusdt@trade",
    derivedFrom: "FX is rebuilt from one EUR rate table: price(A/B) = rate(B) / rate(A).",
    /* True tick-by-tick gold stream (Twelve Data WS, free tier = 1 real-time symbol).
     * Auto-connects on load; polling above remains the fallback if this is
     * unset, unreachable, or the key/quota runs out. */
    twelveDataApiKey: "6c8d081decdb4af99bf262642bcbabcb",
    twelveDataSymbols: ["XAU/USD"]
  },

  /* ---- Which currency is involved, and how ---- */
  currencies: [
    { code: "USD", name: "US Dollar", cb: "Federal Reserve", stance: "Hawkish", bias: 0.90, next: "FOMC 16 Sep 18:00 GMT", note: "~92% odds of a 25bp hike - the strongest G10 driver" },
    { code: "EUR", name: "Euro", cb: "ECB", stance: "Hawkish (hiked 10 Sep)", bias: 0.35, next: "ECB follow-through", note: "A 25bp hike failed to lift the euro against a firm dollar" },
    { code: "JPY", name: "Japanese Yen", cb: "Bank of Japan", stance: "Hawkish", bias: 0.45, next: "BoJ 18 Sep", note: "Hike expected - JPY-positive; carry-unwind risk" },
    { code: "GBP", name: "British Pound", cb: "Bank of England", stance: "Neutral", bias: 0.05, next: "-", note: "Soft with the broad dollar bid" },
    { code: "CHF", name: "Swiss Franc", cb: "SNB", stance: "Neutral", bias: 0.10, next: "-", note: "Safe-haven bid, capped by SNB" },
    { code: "AUD", name: "Australian Dollar", cb: "RBA", stance: "Neutral", bias: -0.15, next: "-", note: "Cleanest risk-sentiment proxy" },
    { code: "NZD", name: "New Zealand Dollar", cb: "RBNZ", stance: "Neutral", bias: -0.20, next: "-", note: "Weakest major this week" },
    { code: "CAD", name: "Canadian Dollar", cb: "Bank of Canada", stance: "Neutral", bias: 0.00, next: "-", note: "Oil-linked; firmer oil is CAD-supportive" }
  ],

  /* ---- FX pair list. Signal = bias(base) - bias(quote): > +0.15 BUY, < -0.15 SELL. */
  fxPairs: [
    { pair: "EUR/USD", base: "EUR", quote: "USD", group: "Major", snap: 1.15484, derived: false },
    { pair: "GBP/USD", base: "GBP", quote: "USD", group: "Major", snap: 1.34917, derived: false },
    { pair: "USD/JPY", base: "USD", quote: "JPY", group: "Major", snap: 154.444, derived: false },
    { pair: "USD/CHF", base: "USD", quote: "CHF", group: "Major", snap: 0.81712, derived: false },
    { pair: "AUD/USD", base: "AUD", quote: "USD", group: "Major", snap: 0.71384, derived: false },
    { pair: "NZD/USD", base: "NZD", quote: "USD", group: "Major", snap: 0.57775, derived: false },
    { pair: "USD/CAD", base: "USD", quote: "CAD", group: "Major", snap: 1.39116, derived: false },
    { pair: "EUR/GBP", base: "EUR", quote: "GBP", group: "Cross", snap: 0.85610, derived: true },
    { pair: "EUR/JPY", base: "EUR", quote: "JPY", group: "Cross", snap: 178.34, derived: true },
    { pair: "GBP/JPY", base: "GBP", quote: "JPY", group: "Cross", snap: 208.35, derived: true },
    { pair: "EUR/CHF", base: "EUR", quote: "CHF", group: "Cross", snap: 0.94364, derived: true },
    { pair: "AUD/JPY", base: "AUD", quote: "JPY", group: "Cross", snap: 110.24, derived: true },
    { pair: "CAD/JPY", base: "CAD", quote: "JPY", group: "Cross", snap: 111.02, derived: true },
    { pair: "CHF/JPY", base: "CHF", quote: "JPY", group: "Cross", snap: 189.02, derived: true },
    { pair: "NZD/JPY", base: "NZD", quote: "JPY", group: "Cross", snap: 89.23, derived: true },
    { pair: "EUR/AUD", base: "EUR", quote: "AUD", group: "Cross", snap: 1.61778, derived: true },
    { pair: "GBP/AUD", base: "GBP", quote: "AUD", group: "Cross", snap: 1.88962, derived: true },
    { pair: "AUD/NZD", base: "AUD", quote: "NZD", group: "Cross", snap: 1.23561, derived: true }
  ],
  pairNote: "Drive each signal from the two currencies involved: BUY when the base currency is stronger than the quote currency. Snapshots marked derived are cross-rates computed from the quoted major rates.",

  /* ---- Macro bias for non-FX instruments (analyst model, -1..+1) ---- */
  macroBias: {
    XAUUSD: -0.55, XAGUSD: -0.55, PLATINUM: -0.30, COPPER: -0.20,
    BRENT: 0.60, WTI: 0.60,
    BTCUSD: -0.45, ETHUSD: -0.70, SOLUSD: -0.75
  },

  /* ---- Trade-plan generator parameters (all levels are ATR multiples) ---- */
  plan: {
    entryOffsetAtr: 0.25,
    slAtr: 1.2,
    tp1Atr: 1.5,
    tp2Atr: 2.5,
    note: "Rule-based plan: entry = live price (market) or price minus/plus 0.25 ATR (pullback limit); SL = 1.2 x ATR; TP1 = 1.5 x ATR; TP2 = 2.5 x ATR. Every level is derived from the measured ATR, so R:R is fixed at 1:1.25 and 1:2.08. This is a systematic template, not a recommendation."
  },

  /* ---- Sessions in Malaysia time (MYT = GMT+8) ---- */
  tz: { name: "Malaysia time (MYT)", offset: "GMT+8" },
  sessions: [
    { k: "Sydney", myt: "05:00-14:00", gmt: "21:00-06:00" },
    { k: "Tokyo", myt: "08:00-17:00", gmt: "00:00-09:00" },
    { k: "London", myt: "15:00-24:00", gmt: "07:00-16:00" },
    { k: "New York", myt: "20:00-05:00", gmt: "12:00-21:00" },
    { k: "London/NY overlap", myt: "20:00-24:00", gmt: "12:00-16:00" }
  ],
  bestWindow: {
    Forex: "Malaysia 15:00-24:00 (London open through the London/NY overlap); the overlap 20:00-24:00 MYT has the tightest spreads.",
    Crypto: "24/7 venue, but liquidity and range peak in the NY window: 21:00-05:00 MYT.",
    Commodity: "NY session 21:00-05:00 MYT for the US futures pits; avoid the Tokyo lull 08:00-17:00 MYT."
  },

  tabs: [
    {
      id: "gold", label: "GOLD · XAU/USD", subtitle: "Spot gold vs USD",
      dirRule: "hawkish = SELL gold, dovish = BUY gold",
      price: { spot: 4281.08, change: -11.18, changePct: -0.26, dayRange: "4,265 - 4,315", note: "Below $4,300 into the FOMC; 5-week low $4,282 hit 14 Sep" },
      macro: [
        { label: "DXY", value: "99.50", delta: "+0.39%", note: "Fifth session of dollar gains" },
        { label: "US 10Y", value: "4.955%", delta: "toward 5.0%", note: "Inflation + fiscal pressure" },
        { label: "Brent", value: "$107.35", delta: "+2.62%", note: "Saudi East-West pipeline still shut" },
        { label: "Sep hike odds", value: "~92%", delta: "25bp", note: "First Fed hike in 3 years" }
      ],
      sentiment: { bias: "HAWKISH", tone: "BEARISH", score: -0.62, confidence: 88, netSignal: "SELL", netPct: -3.96, summary: "Energy-led inflation plus a firm dollar and rising real yields are capping gold into the FOMC. Structural central-bank and ETF demand is the offset.", netNote: "Sum of independent speech estimates; events overlap, so the total is a directional gauge, not an additive forecast." },
      alerts: {
        today: [ { level: "high", text: "FOMC decision + dot plot + press conference (~18:00 GMT). SELL on a hawkish hike, BUY on a hold / dovish dots.", tf: "M5 - H1" }, { level: "high", text: "Brent above $107 keeps the inflation trade alive - feeds the hike case.", tf: "Intraday" }, { level: "med", text: "US 10Y pressing 5.0%: a clean break is a fresh headwind.", tf: "1-3D" } ],
        week: [ { level: "high", text: "BoJ hike Fri 18 Sep adds to the global tightening drag.", tf: "Weekly" }, { level: "med", text: "Watch whether the Fed signals one-and-done (bullish) or a cycle (bearish).", tf: "Weekly" }, { level: "med", text: "Q3 central-bank buying data after 30 Sep - the structural demand test.", tf: "Structural" } ]
      },
      news: [
        { time: "16 Sep", tf: "Intraday", title: "Gold slips to $4,281, down 0.26% into the FOMC", summary: "Third straight weekly loss as the dollar firms and hike bets harden.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.88 },
        { time: "16 Sep", tf: "Intraday", title: "Oil extends rally as the Saudi East-West pipeline stays shut", summary: "Brent ~$107 lifts inflation expectations and hardens the tightening case.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.45 },
        { time: "15 Sep", tf: "1-3D", title: "US 10Y yield pushes toward 5%; DXY gains a fifth session", summary: "Higher real yields raise the opportunity cost of non-yielding bullion.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.35 },
        { time: "14 Sep", tf: "Intraday", title: "Gold slides to a one-month low as oil fans hike bets", summary: "Spot fell 0.8% to $4,312.59, touching its lowest since 7 Aug.", source: "Reuters", url: "https://www.reuters.com/world/india/gold-slips-oil-rally-fans-r…bets-ahead-fed-meeting-2026-09-14/", impact: "bearish", signal: "SELL", impactPct: -0.25 },
        { time: "13 Sep", tf: "Weekly", title: "BoJ expected to hike on Friday (18 Sep)", summary: "Synchronised G3 tightening (ECB hiked 10 Sep) adds to gold's headwind.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.30 },
        { time: "10 Sep", tf: "Structural", title: "Central banks bought a record 288.9t in Q2; August ETF inflows $18B", summary: "Reserve managers and ETF holders leaning the same way - a structural floor.", source: "GoldSilver / WGC", url: "https://goldsilver.com/industry-news/article/gold-price-outlook-september-2026/", impact: "bullish", signal: "BUY", impactPct: 0.55 },
        { time: "14 Sep", tf: "Weekly", title: "ANZ keeps a 12-month gold target of $5,400 despite 3 hikes", summary: "Expects geopolitical uncertainty to keep supporting gold.", source: "Yahoo Finance", url: "https://uk.finance.yahoo.com/news/gold-prices-decline-markets-price-093344058.html", impact: "bullish", signal: "BUY", impactPct: 0.20 }
      ],
      speakers: [
        { name: "FOMC decision (today)", role: "Federal Reserve", side: "hawkish", signal: "SELL", quote: "Consensus 25bp hike; the surprise would be a hold or a dovish dot plot.", impact: "Raises real yields - direct pressure on gold", date: "16 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 1.0, s: 1.0, f: 0.35, impactPct: -0.88 },
        { name: "Kevin Warsh", role: "Fed Chair", side: "hawkish", signal: "SELL", quote: "Hawkish stance; open to raising rates if inflation does not keep declining.", impact: "Forward guidance sets the real-yield path", date: "Sep 2026", source: "LiteFinance", url: "https://www.litefinance.org/blog/analysts-opinions/gold-price-prediction-forecast/daily-and-weekly/", w: 1.0, s: 0.7, f: 0.35, impactPct: -0.61 },
        { name: "ECB", role: "European Central Bank", side: "hawkish", signal: "SELL", quote: "Raised key rates 25bp on 10 September.", impact: "Global tightening cycle - gold headwind", date: "10 Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.9, s: 1.0, f: 0.35, impactPct: -0.79 },
        { name: "Bank of Japan", role: "BoJ", side: "hawkish", signal: "SELL", quote: "Widely expected to raise rates on 18 September.", impact: "Yen-funded carry unwind risk", date: "18 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 0.9, s: 0.7, f: 0.5, impactPct: -0.79 },
        { name: "3 FOMC members", role: "Fed voters", side: "hawkish", signal: "SELL", quote: "Dissented in July, voting for an immediate 25bp hike.", impact: "First 3-way dissent since 2016", date: "Jul 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.8, s: 0.6, f: 0.5, impactPct: -0.60 },
        { name: "Chris Zaccarelli", role: "CIO, Northlight Asset Mgmt", side: "hawkish", signal: "SELL", quote: "With a 0.3% m/m core CPI, the Fed now finds itself with its back against the wall.", impact: "Reinforces the hike case", date: "Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.35, s: 0.4, f: 0.35, impactPct: -0.12 },
        { name: "Madhavi Arora", role: "Lead Economist, Emkay", side: "hawkish", signal: "SELL", quote: "Markets pricing ~70% odds of a hike; an October hike is priced in fully.", impact: "Hawkish path priced further out", date: "Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.35, s: 0.4, f: 0.5, impactPct: -0.18 },
        { name: "Donald Trump", role: "US President", side: "dovish", signal: "BUY", quote: "Again called for lower interest rates, criticising the Fed.", impact: "Political pressure; limited near-term effect", date: "14 Sep 2026", source: "Yahoo Finance", url: "https://uk.finance.yahoo.com/news/gold-prices-decline-markets-price-093344058.html", w: 0.15, s: 0.25, f: 0.15, impactPct: 0.01 },
        { name: "Justin Khoo", role: "Senior Market Analyst, VT Markets", side: "neutral", signal: "NEUTRAL", quote: "Gold could weaken if the hike pushes real yields and the dollar higher.", impact: "Scenario framing, not a directional call", date: "Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.35, s: 0.4, f: 0.15, impactPct: 0.00 }
      ],
      levels: { title: "Analyst technical levels (4H)", resistance: [4376, 4441, 4509, 4577], support: [4313, 4255, 4202, 4157] },
      calendar: [
        { date: "Wed 16 Sep", event: "FOMC decision + dot plot + press conference", importance: "high" },
        { date: "Thu 17 Sep", event: "Initial jobless claims; Philadelphia Fed Mfg Index", importance: "med" },
        { date: "Fri 18 Sep", event: "August industrial production; BoJ rate decision", importance: "high" }
      ],
      pressure: [
        { label: "Hawkish Fed", level: "Very high", w: 92, dir: "down" }, { label: "Real-yield pressure", level: "High", w: 78, dir: "down" },
        { label: "USD pressure", level: "High", w: 72, dir: "down" }, { label: "Oil / inflation", level: "High", w: 70, dir: "down" },
        { label: "Safe-haven bid", level: "Moderate", w: 45, dir: "up" }
      ],
      chart1: { label: "Gold price - recent path (cited anchors)", unit: "USD / troy oz", yMin: 4000, yMax: 5700, points: [ { x: "Jan 2026", y: 5608.35 }, { x: "Jul 2026", y: 4029.08 }, { x: "Sep 3", y: 4488.54 }, { x: "Sep 7", y: 4410.55 }, { x: "Sep 10", y: 4385.00 }, { x: "Sep 14", y: 4312.59 }, { x: "Sep 15", y: 4306.00 }, { x: "Sep 16", y: 4281.08 } ] },
      chart2: { label: "September hike odds (cited snapshots)", unit: "%", yMin: 0, yMax: 100, points: [ { x: "Aug 14", y: 31 }, { x: "Sep 1", y: 70 }, { x: "Sep 5", y: 61 }, { x: "Sep 10", y: 60 }, { x: "Sep 12", y: 90 }, { x: "Sep 14", y: 88 }, { x: "Sep 16", y: 92 } ] },
      chart1Note: "Anchor points only (labelled, sourced). Not a continuous tick feed.", chart2Note: "Snapshots from different sources across the month; read the trend."
    },

    {
      id: "crypto", label: "CRYPTO", subtitle: "BTC / ETH majors",
      dirRule: "hawkish = SELL crypto, dovish = BUY crypto",
      price: { spot: 77700, change: -200, changePct: -0.26, dayRange: "76,800 - 78,000", note: "BTC holding near $77,700 into the FOMC; ETH reported down ~4.3% on the day" },
      macro: [
        { label: "BTC", value: "$77,700", delta: "holding", note: "Holds into the FOMC (ET Markets, 16 Sep)" },
        { label: "ETH", value: "$2,513", delta: "-4.28%", note: "Sell-off on the day (ET Markets, 16 Sep)" },
        { label: "US 10Y", value: "4.955%", delta: "toward 5.0%", note: "Higher discount rate hurts risk assets" },
        { label: "Sep hike odds", value: "~92%", delta: "25bp", note: "Hawkish Fed is crypto's main headwind" }
      ],
      sentiment: { bias: "HAWKISH", tone: "BEARISH", score: -0.55, confidence: 78, netSignal: "SELL", netPct: -2.55, summary: "Crypto trades as a high-beta risk asset: a hawkish Fed lifts real yields and the dollar, draining risk appetite. ETH leads the downside while BTC holds.", netNote: "Reuses the macro speech set (crypto has no native central-bank speakers). Same model; crypto is more rate-sensitive, so BASE is scaled x1.3." },
      alerts: {
        today: [ { level: "high", text: "FOMC decision (~18:00 GMT): a hawkish hike is a SELL for crypto; a hold is a BUY.", tf: "M5 - H1" }, { level: "high", text: "ETH down ~4.3% while BTC is flat - alt underperformance = risk-off rotation.", tf: "Intraday" }, { level: "med", text: "Polymarket prices BTC 74k-76k for 16 Sep at ~46% - the implied downside band.", tf: "Intraday" } ],
        week: [ { level: "high", text: "BoJ decision Fri 18 Sep - another global tightening input for risk assets.", tf: "Weekly" }, { level: "med", text: "ETH 7-day change only +0.22% with mcap $302.5B - flat weekly, fragile.", tf: "Weekly" }, { level: "med", text: "Post-FOMC dollar trend is the dominant driver into month-end.", tf: "Weekly" } ]
      },
      news: [
        { time: "16 Sep", tf: "Intraday", title: "Ethereum reported down ~4.28% on the day", summary: "Alt weakness while BTC holds near $77,700 - risk-off rotation within crypto.", source: "ET Markets", url: "https://economictimes.indiatimes.com/markets/cryptocurrency/ethereum-price/cryptodetail/symbol-eth.cms", impact: "bearish", signal: "SELL", impactPct: -1.10 },
        { time: "16 Sep", tf: "Intraday", title: "Bitcoin holds near $77,700 into the FOMC", summary: "BTC flat but capped; the Fed decision is the near-term trigger.", source: "ET Markets", url: "https://economictimes.indiatimes.com/markets/cryptocurrency/ethereum-price/cryptodetail/symbol-eth.cms", impact: "neutral", signal: "NEUTRAL", impactPct: 0.00 },
        { time: "16 Sep", tf: "Intraday", title: "Polymarket: BTC 74,000-76,000 on 16 Sep priced at ~46%", summary: "Market-implied downside band for the session.", source: "Polymarket", url: "https://polymarket.com/crypto", impact: "neutral", signal: "NEUTRAL", impactPct: 0.00 },
        { time: "14 Sep", tf: "1-3D", title: "Crypto prices trying to hold as rate-hike expectations grow", summary: "BTC opened $76,806 and traded to $77,873; ETH opened $2,475.82.", source: "Yahoo Finance", url: "https://finance.yahoo.com/personal-finance/investing/article/bitcoin-and-ethereum-prices-today-monday-september-14-2026-crypto-prices-trying-to-hold-as-rate-hike-expectations-grow-114245430.html", impact: "bearish", signal: "SELL", impactPct: -0.70 },
        { time: "15 Sep", tf: "Weekly", title: "ETH market cap $302.5B; 7-day change +0.22%", summary: "Flat on the week with high sensitivity to the rate path.", source: "Forbes Advisor", url: "https://www.forbes.com/advisor/investing/cryptocurrency/top-10-cryptocurrencies/", impact: "neutral", signal: "NEUTRAL", impactPct: 0.00 }
      ],
      speakers: [
        { name: "FOMC decision (today)", role: "Federal Reserve", side: "hawkish", signal: "SELL", quote: "Crypto is the highest-beta expression of the rate trade.", impact: "Higher real yields drain risk appetite", date: "16 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 1.0, s: 1.0, f: 0.35, impactPct: -1.14 },
        { name: "Kevin Warsh", role: "Fed Chair", side: "hawkish", signal: "SELL", quote: "Hawkish stance; open to raising rates if inflation does not keep declining.", impact: "Sets the discount rate for all risk assets", date: "Sep 2026", source: "LiteFinance", url: "https://www.litefinance.org/blog/analysts-opinions/gold-price-prediction-forecast/daily-and-weekly/", w: 1.0, s: 0.7, f: 0.35, impactPct: -0.80 },
        { name: "Bank of Japan", role: "BoJ", side: "hawkish", signal: "SELL", quote: "Widely expected to raise rates on 18 September.", impact: "Yen carry unwind hits crypto liquidity", date: "18 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 0.9, s: 0.7, f: 0.5, impactPct: -1.02 },
        { name: "ECB", role: "European Central Bank", side: "hawkish", signal: "SELL", quote: "Raised key rates 25bp on 10 September.", impact: "Global tightening - liquidity headwind", date: "10 Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.9, s: 1.0, f: 0.35, impactPct: -1.02 },
        { name: "Donald Trump", role: "US President", side: "dovish", signal: "BUY", quote: "Again called for lower interest rates, criticising the Fed.", impact: "Dovish jawboning is mildly supportive if it shifts odds", date: "14 Sep 2026", source: "Yahoo Finance", url: "https://uk.finance.yahoo.com/news/gold-prices-decline-markets-price-093344058.html", w: 0.15, s: 0.25, f: 0.15, impactPct: 0.02 }
      ],
      levels: { title: "Market-implied bands (Polymarket, 16 Sep)", resistance: [80000, 78000], support: [76000, 74000] },
      calendar: [
        { date: "Wed 16 Sep", event: "FOMC decision + dot plot + press conference", importance: "high" },
        { date: "Fri 18 Sep", event: "BoJ rate decision", importance: "high" },
        { date: "Fri 18 Sep", event: "US August industrial production", importance: "med" }
      ],
      pressure: [
        { label: "Hawkish Fed", level: "Very high", w: 92, dir: "down" }, { label: "Real-yield pressure", level: "High", w: 76, dir: "down" },
        { label: "USD pressure", level: "High", w: 70, dir: "down" }, { label: "Alt-coin weakness", level: "High", w: 68, dir: "down" },
        { label: "BTC relative strength", level: "Moderate", w: 40, dir: "up" }
      ],
      chart1: { label: "BTC - cited anchors (Sep 2026)", unit: "USD", yMin: 74000, yMax: 80000, points: [ { x: "Sep 1 open", y: 78559.11 }, { x: "Sep 1", y: 77945.97 }, { x: "Sep 14 open", y: 76806.19 }, { x: "Sep 14", y: 77873.33 }, { x: "Sep 15", y: 76918.51 }, { x: "Sep 16", y: 77700 } ] },
      chart2: { label: "BTC implied band probabilities (16 Sep)", unit: "%", yMin: 0, yMax: 100, points: [ { x: "74-76k", y: 46 }, { x: ">78k", y: 21 }, { x: "78-80k", y: 18 }, { x: "72-74k", y: 15 } ] },
      chart1Note: "Anchor points only (Yahoo Finance, Forbes).", chart2Note: "Polymarket implied probabilities - a distribution snapshot, not a forecast."
    },

    {
      id: "forex", label: "FOREX", subtitle: "Majors vs USD",
      dirRule: "hawkish Fed = BUY USD (SELL EURUSD / GBPUSD, BUY USDJPY) ; dovish Fed = the inverse",
      price: { spot: 1.15484, change: -0.0051, changePct: -0.44, dayRange: "1.1520 - 1.1610", note: "EUR/USD pressured by a firmer dollar ahead of the FOMC" },
      macro: [
        { label: "DXY", value: "99.50", delta: "+0.39%", note: "Fifth session of gains - the FX master signal" },
        { label: "USD/JPY", value: "154.44", delta: "+0.54%", note: "Yen slips as the dollar and oil gain" },
        { label: "GBP/USD", value: "1.34917", delta: "-0.25%", note: "Sterling softer with the dollar bid" },
        { label: "Sep hike odds", value: "~92%", delta: "25bp", note: "USD-supportive into the decision" }
      ],
      sentiment: { bias: "HAWKISH", tone: "USD BULLISH", score: 0.52, confidence: 84, netSignal: "SELL", netPct: -3.20, summary: "A hawkish Fed is a dollar-positive event, so the FX expression is BUY USD against EUR, GBP and AUD, and BUY USD/JPY. The ECB hiked on 10 Sep but the dollar still dominates.", netNote: "Signal is quoted for EUR/USD (the headline pair): SELL EUR/USD = BUY USD. Events overlap, so treat the total as directional." },
      alerts: {
        today: [ { level: "high", text: "FOMC decision (~18:00 GMT): BUY USD on a hawkish hike, SELL USD on a dovish hold.", tf: "M5 - H1" }, { level: "high", text: "DXY has gained five sessions - trend-following dollar longs are crowded into the event.", tf: "Intraday" }, { level: "med", text: "USD/JPY 154.44 is sensitive to any BoJ leak or JGB-yield story.", tf: "Intraday" } ],
        week: [ { level: "high", text: "BoJ decision Fri 18 Sep: a hike is JPY-positive (SELL USD/JPY).", tf: "Weekly" }, { level: "med", text: "EUR: post-ECB-hike (10 Sep) the euro failed to hold gains - watch for a dovish repricing.", tf: "Weekly" }, { level: "med", text: "AUD/NZD are the cleanest risk-sentiment proxies this week.", tf: "Weekly" } ]
      },
      news: [
        { time: "16 Sep", tf: "Intraday", title: "Dollar extends gains to a fifth session ahead of the FOMC", summary: "EUR/USD -0.44% at 1.15484; the dollar is the dominant driver into the decision.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.55 },
        { time: "16 Sep", tf: "Intraday", title: "Yen slips as the dollar and oil gain", summary: "USD/JPY +0.54% to 154.44; higher oil worsens Japan's terms of trade.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bullish", signal: "BUY", impactPct: 0.50 },
        { time: "15 Sep", tf: "1-3D", title: "Sterling and antipodeans softer with risk sentiment", summary: "GBP/USD -0.25%, AUD/USD -0.41%, NZD/USD -0.61% - a broad dollar bid.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bearish", signal: "SELL", impactPct: -0.35 },
        { time: "10 Sep", tf: "Weekly", title: "ECB hiked 25bp but the euro failed to hold the gains", summary: "A hawkish ECB is being out-weighed by US rate expectations.", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", impact: "neutral", signal: "NEUTRAL", impactPct: 0.00 },
        { time: "18 Sep", tf: "Weekly", title: "BoJ widely expected to hike on Friday", summary: "A JPY-positive event that would unwind yen-funded carry trades.", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", impact: "bullish", signal: "BUY", impactPct: 0.45 }
      ],
      speakers: [
        { name: "FOMC decision (today)", role: "Federal Reserve", side: "hawkish", signal: "SELL", quote: "A 25bp hike lifts the dollar's rate differential against every G10 currency.", impact: "USD-positive -> EUR/USD lower", date: "16 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 1.0, s: 1.0, f: 0.35, impactPct: -0.95 },
        { name: "Kevin Warsh", role: "Fed Chair", side: "hawkish", signal: "SELL", quote: "Hawkish stance; open to raising rates if inflation does not keep declining.", impact: "Sets the USD rate differential", date: "Sep 2026", source: "LiteFinance", url: "https://www.litefinance.org/blog/analysts-opinions/gold-price-prediction-forecast/daily-and-weekly/", w: 1.0, s: 0.7, f: 0.35, impactPct: -0.66 },
        { name: "ECB", role: "European Central Bank", side: "hawkish", signal: "BUY", quote: "Raised key rates 25bp on 10 September.", impact: "EUR-supportive, but out-weighed by the USD bid", date: "10 Sep 2026", source: "Livemint", url: "https://www.livemint.com/market/stock-market-news/the-us-federal-reserves-policy-meeting-due-on-wednesday-september-16-how-will-it-impact-your-stocks-gold-and-rupee-11789368302533.html", w: 0.9, s: 1.0, f: 0.35, impactPct: 0.45 },
        { name: "Bank of Japan", role: "BoJ", side: "hawkish", signal: "BUY", quote: "Widely expected to raise rates on 18 September.", impact: "JPY-positive -> USD/JPY lower", date: "18 Sep 2026", source: "Trading Economics", url: "https://tradingeconomics.com/commodity/gold", w: 0.9, s: 0.7, f: 0.5, impactPct: 0.60 },
        { name: "Donald Trump", role: "US President", side: "dovish", signal: "BUY", quote: "Again called for lower interest rates, criticising the Fed.", impact: "USD-negative if it shifts rate expectations", date: "14 Sep 2026", source: "Yahoo Finance", url: "https://uk.finance.yahoo.com/news/gold-prices-decline-markets-price-093344058.html", w: 0.15, s: 0.25, f: 0.15, impactPct: 0.02 }
      ],
      levels: { title: "Round-number FX reference levels (not analyst calls)", resistance: [1.1600, 1.1650, 1.1700], support: [1.1500, 1.1450, 1.1400] },
      calendar: [
        { date: "Wed 16 Sep", event: "FOMC decision + dot plot + press conference", importance: "high" },
        { date: "Thu 17 Sep", event: "US jobless claims; Philadelphia Fed Mfg Index", importance: "med" },
        { date: "Fri 18 Sep", event: "BoJ rate decision; US industrial production", importance: "high" }
      ],
      pressure: [
        { label: "Hawkish Fed (USD+)", level: "Very high", w: 92, dir: "up" }, { label: "Real-yield differential", level: "High", w: 76, dir: "up" },
        { label: "Oil / terms of trade", level: "High", w: 66, dir: "up" }, { label: "Risk aversion (USD+)", level: "Moderate", w: 55, dir: "up" },
        { label: "Carry unwind risk", level: "Moderate", w: 48, dir: "down" }
      ],
      chart1: { label: "USD performance vs majors (15 Sep, %)", unit: "%", yMin: 0, yMax: 0.7, points: [ { x: "EUR", y: 0.44 }, { x: "GBP", y: 0.25 }, { x: "JPY", y: 0.54 }, { x: "AUD", y: 0.41 }, { x: "NZD", y: 0.61 } ] },
      chart2: { label: "September hike odds (cited snapshots)", unit: "%", yMin: 0, yMax: 100, points: [ { x: "Aug 14", y: 31 }, { x: "Sep 1", y: 70 }, { x: "Sep 5", y: 61 }, { x: "Sep 10", y: 60 }, { x: "Sep 12", y: 90 }, { x: "Sep 14", y: 88 }, { x: "Sep 16", y: 92 } ] },
      chart1Note: "Derived from the quoted daily moves of each pair (Trading Economics, 15 Sep).", chart2Note: "Snapshots from different sources; read the trend."
    }
  ],

  sources: [
    "Trading Economics - Gold / FX / commodities", "Reuters - Gold one-month low (14 Sep)", "Yahoo Finance - Gold and BTC/ETH (14 Sep)",
    "Livemint - Fed 16 Sep impact", "GoldSilver - Gold Outlook Sept 2026", "LiteFinance - XAU/USD forecast",
    "Forbes Advisor - Top 10 Cryptocurrencies (15 Sep)", "ET Markets - ETH (16 Sep)", "Polymarket - Crypto odds",
    "Investopedia / Fidelity - ATR", "EventStudyTools - Event study methodology", "B2Prime - Gold / Oil / USD correlations"
  ]
};
